# Generated by Django 3.1.1 on 2020-10-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penyelenggara',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_skema', models.CharField(max_length=120)),
                ('kode_skema', models.CharField(max_length=12)),
            ],
        ),
    ]
