# Generated by Django 3.1.1 on 2020-10-07 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skema', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Penyelenggara',
            new_name='Skema',
        ),
    ]
