from django.db import models

class Pegawai(models.Model):
    nik = models.CharField(max_length=12)
    nik_sap = models.CharField(max_length=12)
    nama = models.CharField(max_length=128)
    p_grade = models.CharField(max_length=4,blank=True, null=True)
    job_grade = models.CharField(max_length=4,blank=True, null=True)
    grade_sap = models.CharField(max_length=4,blank=True, null=True)
    nama_jabatan = models.CharField(max_length=128,blank=True, null=True)
    jabatan = models.CharField(max_length=5,blank=True, null=True)
    kode_unitkerja = models.CharField(max_length=10,blank=True, null=True)
    kode_dir = models.CharField(max_length=10,blank=True, null=True)
    kode_komp = models.CharField(max_length=10,blank=True, null=True)
    kode_dept = models.CharField(max_length=10,blank=True, null=True)
    kode_bagian = models.CharField(max_length=10,blank=True, null=True)
    kode_seksi = models.CharField(max_length=10,blank=True, null=True)
    direktorat = models.CharField(max_length=128,blank=True, null=True)
    kompartemen = models.CharField(max_length=128,blank=True, null=True)
    departemen = models.CharField(max_length=128,blank=True, null=True)
    bagian = models.CharField(max_length=128,blank=True, null=True)
    seksi = models.CharField(max_length=128,blank=True, null=True)
    regu = models.CharField(max_length=128,blank=True, null=True)
    poscode = models.CharField(max_length=24,blank=True, null=True)
    postitle = models.CharField(max_length=128,blank=True, null=True)
    alamat = models.CharField(max_length=128,blank=True, null=True)
    kelurahan = models.CharField(max_length=128,blank=True, null=True)
    kecamatan = models.CharField(max_length=128,blank=True, null=True)
    kabupaten = models.CharField(max_length=128,blank=True, null=True)
    provinsi = models.CharField(max_length=64,blank=True, null=True)
    kode_pos = models.CharField(max_length=8,blank=True, null=True)
    lp = models.CharField(max_length=12,blank=True, null=True)
    nik_bp = models.CharField(max_length=10,blank=True, null=True)
    akses_sistem = models.CharField(max_length=3,blank=True, null=True)
